### ISSUE TITLE
Token Balance Placeholders

### ISSUE THREAD

**Issue by Elijeh** [Realizedd/TokenManager#12]
Would it be possible to add a PlaceholderAPI placeholder so the player's token balance is formatted and add a similar placeholder in the language file?

**Comment by Realizedd** [comment]
%tm_tokens% for PlaceholderAPI. Not sure what you mean by adding it to the lang file. Could you elaborate?

**Comment by Elijeh** [comment]
Yes I know about %tm_tokens%. I mean adding a placeholder that formats the balance (1000 > 1k, etc.).

A placeholder like this would be nice for PlaceholderAPI & the language file.

**Comment by Realizedd** [comment]
Will be added in v3.0.5, thanks

**Comment by Realizedd** [comment]
Implemented in 1e9aeb6.

For any token amount placeholder in lang.yml, append _formatted to display it as formatted.

For example,
`balance: '{PREFIX} &7Your token balance is &b%tokens_formatted% token(s)&7.'`
