### ISSUE TITLE
TokenManager shop stealing tokens and not providing the purchase item.

### ISSUE THREAD

**Issue by mibby** [Realizedd/TokenManager#13]
TokenManager v3.0.4-SNAPSHOT

@RealizedMC I'm getting reports that the TokenManager shop is stealing tokens from players and not actually providing the item to the person. It doesn't happen all the time, but had a handful of people lose tokens and not receive keys / hats.

Config
https://paste.ubuntu.com/p/DYyVg6B87C/

Shop
https://paste.ubuntu.com/p/7vTjPhWs3v/

Do you think it may be a problem with ```confirm-purchase: true``` with perhaps the command not running from console after purchase? As this problem didn't appear to exist in TM v2.

**Comment by Realizedd** [comment]
The fact that it happens randomly doesn't make much sense to me. Could you check if those players for sure did not receive the items? And did this also happen in v3.0.3?

**Comment by mibby** [comment]
As far as I know, rewarding was working fine prior to me adding the confirmation to all items with v3.0.3 and earlier versions. Multiple different people reported tokens being taken and not receiving the item, so I'm fairly certain it is an issue somewhere.

**Comment by Realizedd** [comment]
Fixed in 1e9aeb6, apologizes for my dumb mistake.
