### ISSUE TITLE
Support for glow enchant NBT  and hiding all item NBT properties from display.

### ISSUE THREAD

**Issue by mibby** [Realizedd/TokenManager#15]

**Comment by Realizedd** [comment]
Added support for [ItemFlag](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/inventory/ItemFlag.html).

To make an item glow without displaying enchantments in the lore:
`displayed: TRIPWIRE_HOOK 1 unbreaking:10 flags:HIDE_ENCHANTS name:&e&lKeys`

To make an item not display unbreakable or attack damage:
`displayed: DIAMOND_SPADE 1 name:&f&lHats flags:HIDE_UNBREAKABLE,HIDE_ATTRIBUTES lore:&cServer_Resource_Pack|&cRequired_For_Visibility unbreakable:true`

Solved by 7fa82b0

**Comment by mibby** [comment]
Thanks @RealizedMC!

Do you know if it is possible to hide the record name in the lore for cd items being displayed? i.e. ```C418 - 13``` I would like to use the record disc mainly just for the icon.

**Comment by Realizedd** [comment]
I believe those are client-sided, therefore cannot be modified.

**Comment by mibby** [comment]
@RealizedMC Using the plugin BossShopPro, I am able to hide CD lore with their hideflags:all attribute property. So it must be possible.

Could you take a look again please and add support for hiding the CD lore in item display? :)

**Comment by Realizedd** [comment]
Hmm, try adding all the other flags maybe?

**Comment by mibby** [comment]
I have these flags set on all the disc items but it still shows up unfortunately.
```flags:HIDE_UNBREAKABLE,HIDE_ATTRIBUTES,HIDE_ENCHANTS```

Maybe what it does is strip the lore on the item, then sets it with the defined lore you want on the item? In which case, could TokenManager strip all existing lore before setting a custom one?

**Comment by Realizedd** [comment]
HIDE_PLACED_ON could be the right one, since you right click the disc on the note block. I’ve also checked BossShop’s code and it seems to work the same as TokenManager.

**Comment by Realizedd** [comment]
Turns out it's HIDE_POTION_EFFECTS, just tested it. That should do the job.

**Comment by mibby** [comment]
That's it, thanks a bunch!
