### ISSUE TITLE
Confirm-purchase is showing incorrect buy price on confirmation screen.

### ISSUE THREAD

**Issue by mibby** [Realizedd/TokenManager#17]
TokenManager v3.0.5

I have ```confirm-purchase: true``` set on all my shop categories. When I click on an item, it is showing the confirmation price as 40 tokens for every single item, even items that only cost 8 tokens.

Shops.yml - https://paste.ubuntu.com/p/vF8bbHgPQK/

Edit: After a server restart, it now shows the confirmation as 32 for all items. Perhaps it is setting the confirmation screen based on what the first time clicked on costs, then never refreshing it again for others until next restart?

**Comment by Realizedd** [comment]
Solved in 7fa82b0
