### ISSUE TITLE
Min & Max Send Requirements

### ISSUE THREAD

**Issue by Elijeh** [Realizedd/TokenManager#20]
Please add a minimum & maximum token send requirement which can be configured.

Also, I would like to use %tokens_formatted% for these sections of the lang file:
 - 'COMMAND.token.send' | Not sure if this is already possible.
 - 'COMMAND.token.receive' | Not sure if this is already possible.
 - 'COMMAND.tokenmanager.add'
 - 'COMMAND.tokenmanager.remove'
 - 'COMMAND.tokenmanager.set'
 - 'COMMAND.tokenmanager.giveall'
 - 'COMMAND.tokenmanager.add' | Under sub-command-usage.
 - 'COMMAND.tokenmanager.remove' | Under sub-command-usage.

**Comment by Realizedd** [comment]
Oops, forgot to check this. Probably will be added in the next update. For _formatted placeholders, it can be added to any other number placeholders. For example, it would be %amount_formatted% for COMMAND.tokenmanager.add

**Comment by Realizedd** [comment]
Added in 7e96e8b.
