### ISSUE TITLE
%tm_tokens% placeholder broken?

### ISSUE THREAD

**Issue by mibby** [Realizedd/TokenManager#24]
TokenManager compiled as of commit https://github.com/Realizedd/TokenManager/commit/2946b91fc20ead35fdeee80b9dfee54663495ddb
BossShopPro v2.0.0
Paper dev 403 (Spigot 1.13.2)

I use the %tm_tokens% placeholder to display a player's token value in a GUI menu in BossShopPro, alongside other placeholders.

```
    - 'lore:&f&lMoney: &a%balance%#&f&lPoints: &6%balancepoints%#&f&lTokens: &b%tm_tokens%'
```

I just actually noticed that the placeholder stopped working recently. Did it break in a recent commit? It use to work perfectly fine in the menu in a 1.12.2 environment.

The menu displays the balance and points placeholders fine, it's just TokenManager that isn't.

**Comment by Realizedd** [comment]
I haven't made any changes to TokenManager recently, so I doubt it's something on my side. Try testing on 1.12.2 again and see if it still works on that version, so that I can see if it's related to 1.13

**Comment by mibby** [comment]
@Realizedd It does seem to work perfectly fine in my legacy 1.12 environment. 

However quite oddly after a day and an automated server restart, the balance is now showing up again in my menu. Perhaps there is an issue with registering the placeholder sometimes during initialization?

**Comment by Realizedd** [comment]
All I’m doing is using the API provided method, so I would assume it’s something to do with BossShop.

**Comment by mibby** [comment]
Hmm. Maybe it sometimes loads / registers the placeholder after BossShops initializes so it doesn't actually pull up the data? It's quite odd that it flip flops between working and not working.

**Comment by Realizedd** [comment]
I'll close this for now, since it doesn't seem to be related to my code.
