### ISSUE TITLE
Leftover debug - Startup Done.

### ISSUE THREAD

**Issue by mibby** [Realizedd/TokenManager#27]
TokenShop v3.2.0

@Realizedd Whenever you make a purchase in the token shop, console outputs ```Startup Done.```.

Edit: It might actually just be ```Done.``` Logs just show Done while the console itself shows Startup Done.

**Comment by Realizedd** [comment]
It's probably something to do with whatever commands you are executing. I wasn't able to find any messages in the code related to Done.

**Comment by mibby** [comment]
You are absolutely correct. It seems to be related to this here. https://github.com/goncalomb/NBTEditor/blob/63c5a43e973713f1a3ba0a984014eaafda016900/src/main/java/com/goncalomb/bukkit/nbteditor/commands/CommandItemStorage.java#L84

Apologies!
