### ISSUE TITLE
/token top - offline players failed to get name

### ISSUE THREAD

**Issue by andris155** [Realizedd/TokenManager#29]
/token top - offline players failed to get name
![51433196-c716eb80-1c45-11e9-9a72-9a665cf1f4ba](https://user-images.githubusercontent.com/8324198/51457154-98396c00-1d50-11e9-99a7-9139b4d1de7b.png)
Paper 1.13.2

**Comment by Realizedd** [comment]
Is your server in online mode?

**Comment by andris155** [comment]
No. Offline mode server.

**Comment by Realizedd** [comment]
Seems like your data is saved in uuid format. Stop your server, set online-mode in TokenManager config to false, rename your data.yml so it can regenerate a new empty version with the correct data format (change table name if you’re using sql), then start your server.

**Comment by andris155** [comment]
Thank you. This fixed error.
