### ISSUE TITLE
missing id column in MySQL table

### ISSUE THREAD

**Issue by plachta11b** [Realizedd/TokenManager#3]
It is good practice to have id column in case of renaming players.

**Comment by Realizedd** [comment]
I should've when I first designed the plugin, but I believe it's too late to change it now since many people are already using the plugin. Also, since UUIDs don't change, name changes shouldn't be a problem?

**Comment by plachta11b** [comment]
My server is in offline mode because some players had issues with official client. When someone is renaming their character, script is executed and this script change nicknames in all tables (on server backend in python). It works well without issue with many plugins.  I can kick player but restarting server is not way.

In tokenmanager table i can see only two columns
name (primary), tokens

I have doubts about handling rename event properly when name is PRIMARY key of table.

Adding id column should not break backward compatibility.  Just check if there is column and create new if needed.

Script like this should do the job:
> ALTER TABLE `tokenmanager`
ADD `id` int NOT NULL AUTO_INCREMENT UNIQUE FIRST;

(I have not deep knowledge of SQL scripting but it probably always add id for existing players)

**Comment by TomLewis** [comment]
It makes absolutely no sense not to have a unique ID, you should 100% have an auto-increment ID for each row.

**Comment by Realizedd** [comment]
Query for creating table was modified to have an id field in 3407c06.

To add id field to existing table, run these queries:

1. `ALTER TABLE <table name> DROP PRIMARY KEY;`
2. `ALTER TABLE <table name> ADD UNIQUE (uuid);`
3. `ALTER TABLE <table name> ADD id INT NOT NULL AUTO_INCREMENT PRIMARY KEY FIRST;`
