### ISSUE TITLE
Enhancement: Log successful send and sell actions to console

### ISSUE THREAD

**Issue by Justin42** [Realizedd/TokenManager#32]
Hello,
It would be nice to have send and sell actions logged to console. While the command itself is generally logged by the server, it isn't currently possible to tell what result this had. I suggest that when these actions are completed successfully that it be logged to console. This way it is easier to track token transactions.

**Comment by Realizedd** [comment]
Implemented in 5538384.

TokenManager v3.2.3, which was just released, includes this feature. Thanks for the suggestion.
