### ISSUE TITLE
API: Why no addTokens(Player, long) and removeTokens(Player, long) methods?

### ISSUE THREAD

**Issue by Trophonix** [Realizedd/TokenManager#33]
It'd be preferable if I didn't have to check the online-mode of the server in my own plugin to use the add/remove methods of tokenmanager (since I need to know whether to pass uuid/string). 

This would make it more consistent with the rest of the methods and it'd be a really easy addition, just redirect it to setTokens(player, getTokens(player) +- amount).

Thanks!

**Comment by Realizedd** [comment]
Will add in the next version.

**Comment by Trophonix** [comment]
Awesome 😁 I'll look out for the update. Thank you!

> Will add in the next version.
>

**Comment by Realizedd** [comment]
Implemented in 5538384.

TokenManager v3.2.3, which was just released, includes these new methods. Thanks for the suggestion.
