### ISSUE TITLE
Redundant storage values

### ISSUE THREAD

**Issue by Sxtanna** [Realizedd/TokenManager#34]
If a player's balance is zero, you don't need to save it within the file database.

[Relevant Line](https://github.com/Realizedd/TokenManager/blob/master/src/main/java/me/realized/tokenmanager/data/database/FileDatabase.java#L153)

**Comment by Realizedd** [comment]
That would be the case if the default balance was always zero. Since it can be anything, if I skipped saving for zero balance players, they would have a default balance on their next login.
