### ISSUE TITLE
MySQL improve user experience

### ISSUE THREAD

**Issue by plachta11b** [Realizedd/TokenManager#4]
Please can you add feature that create database if database does not exist?

This message

> [TokenManager] Failed to connect to the redis server! Player balance synchronization issues may occur when modifying them while offline.

is spaming log file. Adding option similar to "enabled: false" would be nice.

Editing mysql database does not change in game token count. (I want to modify token amount from web server)

**Comment by Realizedd** [comment]
- Will do
- Will do as well
- This is something that will be too hard to implement with current design (caching the token balance in memory on login/saving on logout). What you could do is enable redis and send to the channel an update cache request with the new balance when you modify the mysql database. ([This](https://github.com/RealizedMC/TokenManager/blob/master/src/main/java/me/realized/tokenmanager/data/database/MySQLDatabase.java#L173))

**Comment by Realizedd** [comment]
- After doing some research, I've found out that it isn't the best practice to create database via code
- Added in 3407c06
- Read above
