### ISSUE TITLE
Name and ID cannot both be blank

### ISSUE THREAD

**Issue by ManuelKahle** [Realizedd/TokenManager#40]
Hey,

I am getting an Error when I try to add the following config lines:
https://pastebin.com/M7J5HWQR

The Error:
https://pastebin.com/1cE28Bp9

**Comment by Realizedd** [comment]
What's your server version?

**Comment by ManuelKahle** [comment]
Paper-278 (MC: 1.15.2)

This Error accrued only when I restart the server.

**Comment by ManuelKahle** [comment]
Do you need any other informations?
