### ISSUE TITLE
Placeholders break on papi reload.

### ISSUE THREAD

**Issue by broken1arrow** [Realizedd/TokenManager#46]
When use /papi reload, your placeholders break. Use mysql  and version 3.2.5. 

If i doo tokenmanager reload it fix the issue.

%tm_tokens%
%tm_top_name_[position]%
%tm_top_tokens_[position]%
%tm_rank%
%tm_tokens_formatted%
%tm_tokens_commas%

**Comment by Realizedd** [comment]
Fixed in 0490603
