### ISSUE TITLE
./Tokens command unformatted

### ISSUE THREAD

**Issue by Justsean2** [Realizedd/TokenManager#47]
Can you add an option to have the /tokens command return your balance with commas so 100,000 rather than 100000?

**Comment by Realizedd** [comment]
You can change the `%amount%` placeholder to `%amount_commas%` in lang.yml.

**Comment by Justsean2** [comment]
That does not work it returns this.
![2021-02-01_17 28 20](https://user-images.githubusercontent.com/74076029/106539486-f0b0b180-64b2-11eb-86b7-0b3b71f3a75e.png)

**Comment by Realizedd** [comment]
For `/token`, it would be `%tokens_commas%`. Append _commas to whatever placeholder in lang.yml to have it formatted with commas.
