### ISSUE TITLE
UUID mismatch when allowing bedrock players on using Geyser

### ISSUE THREAD

**Issue by dig** [Realizedd/TokenManager#48]
The exception in FileDatabase#setup() is thrown when you allow Geyser players on because they have UUIDs which do not match the pattern in ProfileUtil#isUUID(String uuid). This causes tokenmanager to disable on start. I suggest you remove the checking for UUIDs based on server online or not.

Example Geyser UUID:
00000000-0000-0000-0009-000002ef2baa

**Comment by Realizedd** [comment]
Fixed in [1fa57a1](https://github.com/Realizedd/TokenManager/commit/1fa57a1c81ff8ca03a240e1709550c5c6a975365)
