### ISSUE TITLE
[BUG REPORT] Plugin breaking when using geyser (allowing bedrock players)

### ISSUE THREAD

**Issue by ghost** [Realizedd/TokenManager#52]
The cause of the issue seems to be that the plugin stores playerdata in uuid format. when a bedrock player joins they have a prefix since they can use the same names as normal players so for example if a bedrock player was named tobi the person would be given the name .tobi in-game (. is the prefix in my case).

I think that maybe since the plugin cant find the uuid of the person it probably tries to add an empty object & throws a null error? I did notice if I go into the data.yml file & remove the last line thats added that will fix it.

Not sure how to solve this issue, maybe make it so it can store users with a certain prefix (like . in their name since java users cant do that) by name instead of uuid? Though I can see the downsides to it, well its just annoying that the whole plugin breaks because of it.

**Comment by ghost** [comment]
This is a duplicate of #48

**Comment by Realizedd** [comment]
Fixed in [1fa57a1](https://github.com/Realizedd/TokenManager/commit/1fa57a1c81ff8ca03a240e1709550c5c6a975365)
