### ISSUE TITLE
MySQL Cross server WITHOUT redis

### ISSUE THREAD

**Issue by TomLewis** [Realizedd/TokenManager#7]
There is no reason to rely on a redis server when we have MySQL as it is to work cross server, the ENTIRE reason I picked tokenmanager was to have a cross server currency system. Bungee supports ways to update all servers instantly, LuckPerms does it perfectly fine without Redis. 

The only thing I can think that needs to be cached is the top 10 list, I assume your cache is why you decided to need a whole second database storage engine just to make it cross server.

**Comment by Realizedd** [comment]
If you mean plugin messaging, it requires a player / glitchy as well

Also, some people use lilypad, so I didn’t want to make it bungee only. And the old system required a connection per every transaction, which is too much stress on the server.

**Comment by TomLewis** [comment]
So I cant use this plugin cross server without Redis? I would need to install a whole second database server just to do this..
I just don't get it MySQL is completely fine by itself.

**Comment by Realizedd** [comment]
Might work when the server is small, but the connection pool size will continue to grow when there are frequent transactions, and will go over the max connections limit sometimes.

**Comment by TomLewis** [comment]
is that `max_connections` ? Mines set to 300. I max out maybe 60 players at my busiest times on my survival, and the tokens will only be set via mini-games when there will be no more than 20 players at a time, so tokens will be set at game-end and some game events like kill streaks. What I want to use this for is to have people play mini-games to earn Tokens and then spend them on my Survival shop, I see that there is a shop section built in so that Will save time trying to do one with DeluxeMenu and placeholderapi as I planned. 
I just don't want a player to be able to jump between servers and the cache to still have screw up their balance, Like if they quickly move to survival buy what they want and then zip back to the mini-game server where its still cached where it then updated the database with what it was before they spent it.

**Comment by Realizedd** [comment]
I doubt the cache will mess up itself when players switch between servers, as long as the database doesn't crash or something. So the new version shouldn't be a problem with your design at all, except having to use redis.

**Comment by TomLewis** [comment]
New version? Is there one to be released?
I will just try it without redis, I don't want to have to install extra services to use resources and have to setup more firewall rules to allow servers to communicate when theres no need. Leave this ticket open and ill update you on how it reacts in a production environment, What I will do is run it as a test with my users to see if they can break it, if theres a way they will find it haha

**Comment by Realizedd** [comment]
I meant v3 as the new version. And will do, thanks

**Comment by Realizedd** [comment]
Any updates regarding this issue?

**Comment by TomLewis** [comment]
I cant test it until #11 is fixed.

**Comment by Realizedd** [comment]
Seems like there were no issues, so I'll close this for now. Feel free to re-open if you experience any later on.
